name: iOS-ipa-build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - run: flutter --version
      - run: flutter pub get

    
      - name: Install pods
        working-directory: ios
        run: |
          pod install --repo-update


      - name: Flutter iOS build (no codesign)
        run: flutter build ios --release --no-codesign


      - name: Package IPA
        run: |
          set -euo pipefail
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          # use cp -R so we don't move/rename the source
          cp -R "Runner.app" Payload/
          /usr/bin/zip -r -9 FlutterIpaExport.ipa Payload


      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: ${{ github.sha }}
          overwrite: true
          body: "Automated iOS IPA build"


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlutterIpaExport
          path: build/ios/iphoneos/FlutterIpaExport.ipa
